export const projects = [
	{
		id: '5',
		title: 'Law Firm',
		url: 'https://asyousay-attorney.vercel.app/',
		img: '/projects/law-firm.jpeg',
		desc: 'Potential Law Group website.',
		stacks: ['Next.js', 'Sass', 'Swiper.js'],
	},
	{
		id: '2',
		title: 'Fitness Center Project',
		url: 'https://okocha-gym.netlify.app/',
		img: '/projects/gym-project.jpeg',
		desc: 'Potential gym application with the ability to transform it into a fitness e-commerce website.',
		stacks: ['React', 'Sass'],
	},
	{
		id: '3',
		title: 'Crypto Currency',
		url: 'https://crypto-currency-search.netlify.app/',
		img: '/projects/crypto-project.jpeg',
		desc: 'Currency search from API.',
		stacks: ['React', 'Sass', 'Axios'],
	},
	{
		id: '4',
		title: 'Tip Calculator',
		url: 'https://tip-calculator-front-end-mentor.netlify.app/',
		img: '/projects/splitter.png',
		desc: 'Front-end Mentor Challange.',
		stacks: ['Javascript', 'HTML', 'CSS'],
	},
	{
		id: '1',
		url: 'https://pizza-restaurant-mockup.netlify.app/',
		title: 'Pizzeria',
		img: '/projects/pizza.jpeg',
		desc: 'Potential pizza restaurant website.',
		stacks: ['React', 'Sass'],
	},
];
