import Head from 'next/head';

export default function Home() {
	return (
		<div className='homepage'>
			<Head>
				<title>Replace Me</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<section className='main__section'>
				<div className='main__section__wrapper'>
					<div className='container container__left'>
						<h1>I`m Left</h1>
					</div>
					<div className='container container__right'>
						<h1>I`m right</h1>
					</div>
				</div>
			</section>
		</div>
	);
}
